Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

AllCops:
  NewCops: enable
  Exclude:
    - 'lib/spiker/generators/templates/**'
    - 'exe/spiker'
    - 'spiker.gemspec'